### ISSUE TITLE
Not compatible with Java 8

### ISSUE THREAD

**Issue by draco1023** [ximtech/jasypt-encrypt-plugin#2]
```
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve io.github.ximtech.jasypt-encrypt-plugin:jasypt-encrypt-plugin:1.0.1.
     Required by:
         project : > io.github.ximtech.jasypt-encrypt-plugin:io.github.ximtech.jasypt-encrypt-plugin.gradle.plugin:1.0.1
      > No matching variant of io.github.ximtech.jasypt-encrypt-plugin:jasypt-encrypt-plugin:1.0.1 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '7.6.1' but:
          - Variant 'apiElements' capability io.github.ximtech.jasypt-encrypt-plugin:jasypt-encrypt-plugin:1.0.1 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 17 and the consumer needed a runtime of a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.6.1')
          - Variant 'javadocElements' capability io.github.ximtech.jasypt-encrypt-plugin:jasypt-encrypt-plugin:1.0.1 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.6.1')
          - Variant 'runtimeElements' capability io.github.ximtech.jasypt-encrypt-plugin:jasypt-encrypt-plugin:1.0.1 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 17 and the consumer needed a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.6.1')
          - Variant 'sourcesElements' capability io.github.ximtech.jasypt-encrypt-plugin:jasypt-encrypt-plugin:1.0.1 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.6.1')
```

Can we downgrade sourceCompatibility and targetCompatibility to Java 8 ?

**Comment by ximtech** [comment]
Hi. Try version 1.0.2

**Comment by draco1023** [comment]
```
> Failed to apply plugin 'io.github.ximtech.jasypt-encrypt-plugin'.
   > Could not create task ':cloud-uaa:encryptProperties'.
      > Could not create task of type 'EncryptPropertiesFileTask'.
         > Could not initialize class com.github.jasypt.encrypt.tasks.file.EncryptPropertiesFileTask_Decorated
```

```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.github.jasypt.encrypt.tasks.file.EncryptPropertiesFileTask_Decorated
	at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:1913)
```

**Comment by ximtech** [comment]
Yep, my fault. Fixed in version 1.0.3

**Comment by draco1023** [comment]
Still not working for multi-project. The filtering rules will not take effect on sub-projects.

https://github.com/ximtech/jasypt-encrypt-plugin/blob/a6c05b84f0031f6b3397f57d0dd78c549a15ef1d/src/main/java/com/github/jasypt/encrypt/tasks/file/PropertiesFileAwareTask.java#L105-L108

**Comment by ximtech** [comment]
According to the PR: #3
Created release version: 1.1.3
